spring.application.name=packetshop

server.address=127.0.0.1
server.port=8080

spring.datasource.url=jdbc:h2:file:./data/packetshop;MODE=PostgreSQL;DATABASE_TO_UPPER=false
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

