create table pickup_groups (
    id bigint generated by default as identity primary key,
    pickup_number integer not null,
    customer_id bigint not null,
    total_packet_count integer not null,
    remaining_packet_count integer not null,
    status varchar(20) not null,
    created_at timestamp not null default current_timestamp,
    closed_at timestamp,

    constraint fk_pickup_groups_customer
        foreign key (customer_id) references customers(id),

    constraint chk_pickup_groups_total_packet_count
        check (total_packet_count > 0),

    constraint chk_pickup_groups_remaining_packet_count
        check (remaining_packet_count >= 0),

    constraint chk_pickup_groups_remaining_not_more_than_total
        check (remaining_packet_count <= total_packet_count),

    constraint chk_pickup_groups_status
        check (status in ('OPEN', 'CLOSED')),

    constraint chk_pickup_groups_closed_at
        check (
            status = 'OPEN'
            or closed_at is not null
            ),

    CONSTRAINT chk_pickup_groups_open_remaining
        CHECK (
            (status = 'OPEN' AND remaining_packet_count > 0)
                OR
            (status = 'CLOSED' AND remaining_packet_count = 0)
            )
);