create table pickup_events (
    id bigint generated by default as identity primary key,
    pickup_group_id bigint not null,
    event_type varchar(30) not null,
    packet_count integer not null,
    created_at timestamp not null default current_timestamp,

    constraint fk_pickup_group_id
        foreign key (pickup_group_id)
        references pickup_groups(id),

    constraint chk_pickup_events_event_type
        check (event_type IN ('RECEIVED', 'COLLECTED', 'SENT_BACK')),

    constraint chk_pickup_events_packet_count
        check ( packet_count > 0 )
);